# Setup the MongoDB
dbdata:
  volumes:
    - /data/db
  image: debian:wheezy
  command: /bin/true
enrolldb:
  image: mongo:2.4.14
  volumes_from: 
    - dbdata
  
# Setup the backend app
app:
  links: 
    - enrolldb:mongo
  environment:
    VIRTUAL_HOST: '*/app/*'
  image: namehta/enrollment-app:tomcat 

# Setup the frontend app  
ui:
  environment:
    VIRTUAL_HOST: demoapp.example.com
    BALANCE: roundrobin
  image: namehta/enrollment-ui
  
# Setup the proxy
haproxy:
  links:
    - app
    - ui
  environment:
    BACKEND_PORT: 5000
  ports:
     - "80:80"
     - "70:70"
  image: tutum/haproxy